### ISSUE TITLE
Please support amazon.de

### ISSUE THREAD

**Issue by TobiX** [karldreher/AlwaysSmile#1]
AFAICS, it works the same as on amazon.com:

amazon.de :arrow_right: smile.amazon.de

**Comment by karldreher** [comment]
Thanks for your input...I'm just glad for the interest!  I will definitely include this in the next release, I would like to add Chrome support while I'm at it too.

**Comment by karldreher** [comment]
Hi, done in #2 .  Planning to release to Firefox and Chrome store soon!

**Comment by karldreher** [comment]
update:  released to firefox AMO store, will be updating to Firefox clients as soon as it's approved.
Chrome release still pending, will require better icons.
