### ISSUE TITLE
Chrome Store is giving a security warning on this extension

### ISSUE THREAD

**Issue by kenijo** [karldreher/AlwaysSmile#22]
Hello,

When adding this extension, the Chrome Store is providing a popup warning saying "This extension is not trusted by Enhanced Safe Browsing"

Once installed, the same warning shows up in the Chrome Extension Manager.

**Comment by karldreher** [comment]
Hi @kenijo , thank you very much for letting me know!  I didn't know this was happening.  

Unfortunately, this may be somewhat out of my control.  From what I'm reading, I don't see any misconfiguration that is leading to this message.  If I had to speculate, it could be related to https://github.com/karldreher/netflixplus/issues/8 ; from reading [this site](https://security.googleblog.com/2021/06/new-protections-for-enhanced-safe.html) I'm wondering if I don't fit into Google's category of "a developer who follows the Chrome Web Store Developer Program Policies" with this _other_ extension having been banned in the past.  

That said, I will leave this issue open in case:

- The issue will go away in time (I hope)
- There is a fix within the manifest (which does not imply moving to manifest v3 yet) that can be applied.

If you can think of a way to fix this, a PR or further discussion would be welcome.

**Comment by kenijo** [comment]
Thanks for checking in. I read the Developer Program Policies and came up with the same conclusion as you.
The issue is most likely one of the following: the take down of your past extension, maybe how new the extension is, or the lack of user rating.

**Comment by karldreher** [comment]
Closed issue as behavior is no longer observed.
